@extends('layouts.app')
@section('title','ETF Strategy Dashboard')
@section('content')
<div class="container"><div class="top"><div><h1>ETF 配息策略監控</h1><div class="muted">TWSE 真實資料・Laravel Server-side・每 5 分鐘自動更新</div></div><div><div class="muted">可投入帳戶金額</div><input id="account" type="number" min="0" step="1000" value="{{ number_format($accountAmount,0,'.','') }}"> <button id="save">更新並分析</button></div></div>
<div class="panel"><span id="status">初始化中…</span><span class="muted" id="updated" style="margin-left:15px"></span></div>
<div class="cards"><div class="card"><div class="muted">本月尚未除息候選</div><div class="n" id="candidate">0</div></div><div class="card"><div class="muted">買進候選</div><div class="n" id="buy">0</div></div><div class="card"><div class="muted">賣出提醒</div><div class="n" id="sell">0</div></div><div class="card"><div class="muted">預估最高股利</div><div class="n" id="dividend">NT$0</div></div></div>
<div class="panel"><h2>策略分析</h2><div class="muted" style="margin-bottom:10px">買進：今天仍在最後買進日前且帳戶可買至少 1 張。賣出：持倉已領股利，且目前股價產生的價差大於已領股利。此系統不送出委託。</div><table><thead><tr><th>代號</th><th>名稱</th><th>現價</th><th>除息日</th><th>最後買進日</th><th>發放日</th><th>配息</th><th>可買</th><th>投入</th><th>預估股利</th><th>報酬/價差</th><th>訊號</th></tr></thead><tbody id="rows"><tr><td colspan="12">讀取中…</td></tr></tbody></table></div></div>
@endsection
@push('scripts')<script>const dataUrl='{{ route('dashboard.data') }}',refreshUrl='{{ route('dashboard.refresh') }}';const money=n=>Number(n||0).toLocaleString('zh-TW',{maximumFractionDigits:2});const date=s=>s?new Date(s).toLocaleDateString('zh-TW'):'-';async function load(){try{const r=await fetch(dataUrl,{cache:'no-store'});const d=await r.json();const a=d.results||[];document.getElementById('candidate').textContent=a.filter(x=>x.signal==='BUY_CANDIDATE').length;document.getElementById('buy').textContent=a.filter(x=>x.signal==='BUY_CANDIDATE').length;document.getElementById('sell').textContent=a.filter(x=>x.signal==='SELL_ALERT').length;document.getElementById('dividend').textContent='NT$'+money(Math.max(...a.map(x=>Number(x.estimated_dividend||0)),0));document.getElementById('updated').textContent='最後更新：'+new Date(d.updated_at).toLocaleString('zh-TW');document.getElementById('status').textContent='● 系統正常';document.getElementById('rows').innerHTML=a.length?a.map(x=>{const c=x.signal==='BUY_CANDIDATE'?'buy':x.signal==='SELL_ALERT'?'sell':x.signal==='HOLD'?'hold':'wait';return `<tr><td>${x.etf.code}</td><td>${x.etf.name}</td><td>${money(x.quote_price)}</td><td>${date(x.ex_dividend_date)}</td><td>${date(x.last_buy_date)}</td><td>${date(x.pay_date)}</td><td>${money(x.etf.dividends?.[0]?.dividend_amount||x.estimated_dividend/(x.shares||1))}</td><td>${money(x.shares)} (${x.lots}張)</td><td>NT$${money(x.investment_amount)}</td><td>NT$${money(x.estimated_dividend)}</td><td>${x.capital_gain===null?'-':'NT$'+money(x.capital_gain)}</td><td class="${c}">${x.signal}</td></tr>`}).join(''):'<tr><td colspan="12">目前沒有策略結果；請先執行更新。</td></tr>'}catch(e){document.getElementById('status').textContent='資料讀取失敗：'+e.message}}document.getElementById('save').onclick=async()=>{const token=document.querySelector('meta[name=csrf-token]').content;const amount=document.getElementById('account').value;document.getElementById('status').textContent='更新 TWSE 資料中…';await fetch(refreshUrl,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':token},body:JSON.stringify({account_amount:amount})});await load()};load();setInterval(load,300000);</script>@endpush
